"""LLM 설정 도메인이 외부 저장소에 요구하는 계약."""
from typing import Protocol


class RuntimePolicyRepository(Protocol):
    def load(self) -> dict[str, object] | None: ...

    def save(self, policy: dict[str, object]) -> None: ...


class AgyStatusLineSettings(Protocol):
    def is_installed(self) -> bool: ...

    def install(self) -> str: ...


class AgyUsagePort(Protocol):
    def read(self) -> dict[str, object]: ...


class GoogleModelCatalogPort(Protocol):
    def list_models(self) -> list[dict[str, object]]: ...


class GoogleQuotaPort(Protocol):
    def authorization_url(self) -> str: ...
    def complete(self, code: str, state: str) -> None: ...
    def status(self) -> dict[str, object]: ...
    def read(self) -> dict[str, object]:
        """프로젝트 tier 의 모델별 한도. 값이 없는 칸은 None, -1 은 무제한.

        ``{"projectId", "checkedAt", "tier", "billingEnabled",
        "quotas": [{"model", "rpm", "tpm", "rpd", "recentTokens"}]}``
        """
        ...
    def set_client_secret(self, client_secret: str) -> None: ...
