from typing import Protocol

from .models import RecipeInputSnapshot, RecipeRevision


class RecipeRepository(Protocol):
    def commit(self, revision: RecipeRevision) -> RecipeRevision: ...
    def load_head(self, recipe_id: str) -> RecipeRevision | None: ...
    def head_id(self, recipe_id: str) -> str | None: ...
    def list_for_scaffold(self, scaffold_id: str) -> list[RecipeRevision]: ...
    def list_for_document(self, doc_id: str) -> list[RecipeRevision]: ...


class RecipeInputReader(Protocol):
    def readiness(self, doc_id: str, scaffold_id: str | None) -> tuple[list[str], RecipeInputSnapshot | None]: ...


class RecipeExtractor(Protocol):
    async def extract(self, snapshot: RecipeInputSnapshot) -> dict: ...
